project: 
  type: website

website: 
  page-navigation: true
  title: "PhEpiGit" 
  site-url: "https://www.klinikum.uni-heidelberg.de/en/kliniken-institute/kliniken/zentrum-fuer-innere-medizin-krehl-klinik/dept-of-clinical-pharmacology-and-pharmacoepidemiology" 
  repo-url: "https://pharmacoepidemiology-ukhd.github.io/SOPGitHub"
  #repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "white"
    #logo: logo.svg
    logo: logo.png
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://www.klinikum.uni-heidelberg.de/en/kliniken-institute/kliniken/zentrum-fuer-innere-medizin-krehl-klinik/dept-of-clinical-pharmacology-and-pharmacoepidemiology
        text: "UKHD"
      - icon: github
        href: https://github.com/Pharmacoepidemiology-UKHD
        text: "PhEpi"

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/initial.qmd
        text: Overall flowchart
      - href: content/become_part.qmd
        text: Joining the PhEpiGit
      - href: content/new_repo.qmd
        text: Creating Your First Repository
      - href: content/copy_repo.qmd
        text: Cloning GitHub Repositories to Your Local Machine
      - href: content/commit_push_main.qmd
        text: Committing and Pushing - origin/main Branch
      - href: content/clon_git.qmd
        text: Cloning an existing repository from GitHub
      - href: content/newbranchcommit.qmd
        text: Committing and Pushing – new Branch
      - href: content/acceptpull.qmd
        text: Checking and accepting a pull request
      - href: content/definitions.qmd
        text: Terms, definitions and abbreviation
      - href: content/project_template.qmd
        text: Project template

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
